#!/usr/bin/env python3
"""Detect VERBATIM drift across the collector fleet, by hash and not by eye.

The fleet standard is a set of files that must be byte-identical in every
collector repository. Nothing enforced that, and the fleet had silently split
into two generations that disagreed on five of them -- including
`.github/copilot-instructions.md`, where one generation carried a copy of the
predictor guidelines under the canonical filename.

This script is deliberately dependency-free and read-only, so it runs from any
checkout on any machine, including a corporate Windows box:

    python scripts/check_verbatim_drift.py ../collector_*         # audit a fleet
    python scripts/check_verbatim_drift.py --write-manifest ...   # record a baseline

`--write-manifest` records the current agreed hashes in VERBATIM_MANIFEST.md.
Without it, the script compares the fleet against that manifest and exits 1 on
any disagreement, so drift is a build failure rather than a discovery.

Hashes are Git blob hashes (`git hash-object`), so any value here can be
checked by hand with Git alone and without this script.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

# Files that must be byte-identical in every collector repository.
VERBATIM_FILES = (
    ".github/copilot-instructions.md",
    ".github/prompts/onboard-new-api.prompt.md",
    ".vscode/launch.json",
    ".vscode/settings.json",
    ".gitignore",
    "scripts/__init__.py",
)

# Directories whose every file must be byte-identical.
VERBATIM_TREES = (".github/skills", ".github/prompts")

MANIFEST = Path(__file__).resolve().parents[1] / "VERBATIM_MANIFEST.md"


def blob_hash(path: Path) -> str:
    """Reproduce `git hash-object` without invoking Git."""
    body = path.read_bytes()
    return hashlib.sha1(b"blob %d\0" % len(body) + body).hexdigest()


def collect(repo: Path) -> dict[str, str]:
    found: dict[str, str] = {}
    for rel in VERBATIM_FILES:
        target = repo / rel
        if target.is_file():
            found[rel] = blob_hash(target)
    for tree in VERBATIM_TREES:
        root = repo / tree
        if not root.is_dir():
            continue
        for target in sorted(root.rglob("*")):
            if target.is_file():
                found[target.relative_to(repo).as_posix()] = blob_hash(target)
    return found


def read_manifest() -> dict[str, str]:
    if not MANIFEST.is_file():
        return {}
    pattern = re.compile(r"^\| `([^`]+)` \| `([0-9a-f]{40})` \|")
    expected = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            expected[match.group(1)] = match.group(2)
    return expected


def write_manifest(expected: dict[str, str], repos: list[Path]) -> None:
    lines = [
        "# VERBATIM manifest",
        "",
        "Generated by `scripts/check_verbatim_drift.py --write-manifest`.",
        "Every file below must be byte-identical in every collector repository.",
        "Values are Git blob hashes, so `git hash-object <path>` checks any row by hand.",
        "",
        "## Authority",
        "",
        "Upstream authority: `guimasuko/collector_template`.",
        "",
        "**Upstream SHA used for this baseline: NOT RECORDED.** That repository was not",
        "reachable from the environment that generated this manifest, so these hashes",
        "record what the fleet agreed on among itself, not confirmed upstream equality.",
        "Re-run against the authority once access exists and record the SHA here.",
        "",
        "## Expected hashes",
        "",
        "| Path | Git blob hash |",
        "| --- | --- |",
    ]
    lines += [f"| `{path}` | `{digest}` |" for path, digest in sorted(expected.items())]
    lines += [
        "",
        "## Repositories covered",
        "",
    ]
    lines += [f"- `{repo.name}`" for repo in sorted(repos, key=lambda r: r.name)]
    lines.append("")
    MANIFEST.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("repos", nargs="+", type=Path, help="collector checkouts to audit")
    parser.add_argument(
        "--write-manifest",
        action="store_true",
        help="record the fleet's agreed hashes instead of checking against them",
    )
    args = parser.parse_args(argv)

    repos = [r for r in args.repos if (r / "main.py").is_file()]
    if not repos:
        print("no collector checkouts found (looked for main.py)", file=sys.stderr)
        return 2

    seen: dict[str, dict[str, list[str]]] = {}
    for repo in repos:
        for rel, digest in collect(repo).items():
            seen.setdefault(rel, {}).setdefault(digest, []).append(repo.name)

    drifted = {rel: variants for rel, variants in seen.items() if len(variants) > 1}
    missing = {
        rel: sorted({r.name for r in repos} - {n for names in variants.values() for n in names})
        for rel, variants in seen.items()
    }

    if args.write_manifest:
        if drifted:
            print("refusing to record a manifest while the fleet disagrees:", file=sys.stderr)
            for rel, variants in sorted(drifted.items()):
                print(f"  {rel}", file=sys.stderr)
                for digest, names in sorted(variants.items()):
                    print(f"    {digest}  {', '.join(sorted(names))}", file=sys.stderr)
            return 1
        write_manifest({rel: next(iter(v)) for rel, v in seen.items()}, repos)
        print(f"recorded {len(seen)} hashes across {len(repos)} repositories -> {MANIFEST.name}")
        return 0

    status = 0
    for rel, variants in sorted(drifted.items()):
        status = 1
        print(f"DRIFT {rel}")
        for digest, names in sorted(variants.items()):
            print(f"  {digest}  {', '.join(sorted(names))}")

    expected = read_manifest()
    for rel, digest_map in sorted(seen.items()):
        want = expected.get(rel)
        if want and want not in digest_map:
            status = 1
            print(f"DRIFT {rel}: manifest expects {want}, fleet has {sorted(digest_map)}")

    for rel, absent in sorted(missing.items()):
        if absent:
            status = 1
            print(f"MISSING {rel}: {', '.join(absent)}")

    if status == 0:
        print(f"OK: {len(seen)} VERBATIM paths identical across {len(repos)} repositories")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
